# docker-compose.yml
version: "3"
services:
  app:
    build: ./server
    depends_on:
      - database
    ports:
      - 4000:4000 # make sure we don't have another mongo container running on same port
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: root
  client:
    build: ./client
    image: react_client
    links:
      - app
    working_dir: /home/node/app/client
    volumes:
      - ./:/home/node/app
    ports:
      - 5173:5173
    command: npm run start
    env_file:
      - ./client/.env

  database:
    image: mongo
    volumes:
      - ./db_data/:/data/db/
    ports:
      - 3030:27017

volumes:
  database: